plugins:
  - jest
env:
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
# настройки для имён dirmana/filename при использовании модулей
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-console: 0
  import/extensions: 0
